[workspace]
resolver = "2"

members = [
    "dao",
    "erc1155",
    "fungible-token",
    "gear-feeds-router",
    "nft-example",
    "nft-marketplace/marketplace",
    "nft-marketplace/nft",
    "non-fungible-token",
    "ping",
]
