[workspace]
resolver = "2"

members = [
    "on-chain-nft",
    "dao",
    "dao-light",
    "erc1155",
    "fungible-token",
    "gear-feeds-router",
    "lottery",
    "nft",
    "nft-marketplace",
    "ping",
    "escrow"
]
