[workspace]
resolver = "2"

members = [
    "dao",
    "erc1155",
    "fungible-token",
    "gear-feeds-router",
    "nft-example",
    "non-fungible-token",
    "ping",
    "escrow"
]

[profile.release]
lto = true
opt-level = "s"
