[workspace]
resolver = "2"

members = [
    "fungible-token",
    "gear-feeds-router",
    "non-fungible-token",
    "nft-example",
    "fungible-token-messages",
    "curve-amm",
]

[profile.release]
lto = true
opt-level = "s"
