[package]
name = "derive_trait"
version = "0.1.0"
edition = "2018"

[dependencies]
syn = { version = "1.0" }
quote = "1.0"
proc-macro2 = "1"
utils = { path = "../utils/" }
convert_case = { vesion = "0.5.0" }


[lib]
name = "derive_trait"
path = "src/lib.rs"
proc-macro = true


