[package]
name = "modifier"
version = "0.1.0"
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["parsing", "full", "visit", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1"
convert_case = { vesion = "0.5.0" }


[lib]
name = "modifier"
path = "src/lib.rs"
proc-macro = true
