[package]
name = "multisig-wallet"
version = "0.1.0"
edition = "2021"
authors = ["Gear Technologies"]
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"] }
multisig-wallet-io = { path = "io" }
primitive-types = { version = "0.11.1", default-features = false, features = ["scale-info"]}
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" }